### ISSUE TITLE
Browser.localhost setting ignored (or broken) when submitting a form

### ISSUE THREAD

**Issue by naugtur** [assaf/zombie#1003]
`Browser.localhost("localhost:9999", 19999);`

The page that loads successfully has a form that gets posted to the second url. Works fine without https urls, when using Browser.localhost to fake https, I get the errors. Debug log:

```
 zombie GET http://localhost:9999/authgate/code?redirect_uri=https://example.com => 200 +78ms
  zombie Loaded document http://localhost:9999/authgate/code?redirect_uri=https://example.com +66ms
  zombie Event loop is empty +10ms
  zombie Submit form to https://localhost:9999/authgate/redirect +9ms
  zombie Opened window https://localhost:9999/authgate/redirect  +46ms
  zombie Resource error +12ms Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1032:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
  zombie TypeError: socket hang up
    at /home/zb/repo/_git/ms-wopi/node_modules/zombie/lib/pipeline.js:89:15
    at tryCatcher (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:670:18)
    at Async._drainQueue (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17) +4ms
Fatal TypeError: socket hang up
    at /home/zb/repo/_git/ms-wopi/node_modules/zombie/lib/pipeline.js:89:15
    at tryCatcher (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/promise.js:670:18)
    at Async._drainQueue (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/zb/repo/_git/ms-wopi/node_modules/zombie/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by assaf** [comment]
Did you set your server to accept HTTP and HTTPS on the same port?

**Comment by naugtur** [comment]
It was supposed to be used just for https urls and docs say Browser.localhost is useful for making https urls resolve to localhost http. Having read the docs I expected both http and https urls to be resolved to http://localhost:9999

**Comment by assaf** [comment]
Where does it say that?

**Comment by naugtur** [comment]
I didn't read the first two sentences of https://github.com/assaf/zombie#browserlocalhosthost-port too carefully and got the conclusion: "it handles http/s and it translates ports". My bad.
