### ISSUE TITLE
unable to open a headless browser using zombie in Python

### ISSUE THREAD

**Issue by KumMadhu** [assaf/zombie#1005]
Simple code I used:
from zombie.browser import Browser
b = Browser()
b.visit("https://isam9sp-lmi/core/login")

It's returning error as below:

Traceback (most recent call last):
  File "C:\Kepler\ISAM9Automation\SAMLAutomation\TestHeadlessBrowser.py", line 14, in test1
    b = Browser()
  File "C:\Python27\lib\site-packages\zombie\browser.py", line 32, in __init__
    server = ZombieProxyServer()
  File "C:\Python27\lib\site-packages\zombie\proxy\server.py", line 58, in ZombieProxyServer
    instances[cls] = cls(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zombie\proxy\server.py", line 98, in __init__
    stderr=subprocess.STDOUT
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by assaf** [comment]
This error isn't coming from Zombie. Zombie doesn't contain any Python code.

**Comment by KumMadhu** [comment]
Agree. I am coding in Python to open a headless browser using Zombie library. Please help me to resolve this. Thanks!

**Comment by assaf** [comment]
I have no experience with Python and Windows.

**Comment by jokeyrhyme** [comment]
I think you have posted this question in the wrong place.

The python wrapper for Zombie is a separate and unaffiliated project: https://github.com/ryanpetrello/python-zombie

**Comment by KumMadhu** [comment]
Thanks...however it doesn't seem to be resolved in that thread as well.

**Comment by dinuduke** [comment]
@KumMadhu is your problem solved. i got struck at same problem. if  anyone solved above problem in python can guide me. thanks in advance.
