### ISSUE TITLE
Ignore self signed certificates

### ISSUE THREAD

**Issue by alexserver** [assaf/zombie#1021]
I'm having this problem visiting a self signed certificate (https in dev environment)
```
DEBUG=zombie node zombie.js
  zombie Opened window https://www.example.com/ +0ms
  zombie Resource error +77ms Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:585:8)
  zombie TypeError: self signed certificate
    at /Users/alexserver/dev/play/scripts/node_modules/zombie/lib/pipeline.js:89:15
    at tryCatcher (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/promise.js:672:18)
    at Async._drainQueue (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alexserver/dev/play/scripts/node_modules/zombie/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17) +12ms
```

This is the code I'm attemping to running.
```
const browser = new Browser();
var url = 'https://www.example.com';
browser.visit(url);
```

This is redirected to localhost via /etc/hosts (not zombie).
I'm having an apache server using a fake certificate https virtual server.

How can I ignore ssl errors like with phantomjs ?

**Comment by chaowei** [comment]
I am having the same problem, please give a solution to ignore https certificate verification.
Thanks!

**Comment by mamapitufo** [comment]
you can add `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'` before you call `.visit()` to turn off certificate chain validation.

**Comment by StefanoDeVuono** [comment]
Try this:

    const browser = new Browser({strictSSL: false});
