### ISSUE TITLE
Opening and closing several zombie tabs destroys the browser and crashes completely

### ISSUE THREAD

**Issue by mwiegant** [assaf/zombie#1029]
I'm using zombie to check that our servers are up and that the services on our servers are also up.  I'm running 2 tests right now in each testing cycle. Each test lasts about 20 seconds and each testing cycle begins 3 minutes after the last one began. Since the entire testing cycle takes less than a minute, there should be no conflict between testing cycles overlapping. Each test runs the code below.

```
brower = browser  ||  new Zombie();
browser.visit( mySite, function() {

    setTimeout(function() {

        browser.wait( function() {

            // the test query
            var result = browser.evaluate('document.title');

            // check for the value of the result
            if (result === expectedResult) {
                return cb(null, result);
            } else {
                return cb("ERROR: Unexpected title: " + result, null);
            }

        });

    }, 5000);

});
```

At the conclusion of running each test, I run the code below, for thoroughness.

```
// reset the browser
browser.tabs.closeAll();
```

I have the tests above running in a nodeJS server. I usually don't have a problem running through the tests the first time, but on the second time running through the tests zombieJS has a tendency to crash with the error shown below:

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: This browser has been destroyed
    at EventQueue.onerror (/Users/Max/Documents/site-status/node_modules/zombie/lib/eventloop.js:385:7)
    at HTMLDocument.DOM.Document.raise (/Users/Max/Documents/site-status/node_modules/zombie/lib/dom/jsdom_patches.js:207:22)
    at XMLHttpRequest.raise (/Users/Max/Documents/site-status/node_modules/zombie/lib/xhr.js:250:27)
    at callListeners (/Users/Max/Documents/site-status/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:172:14)
    at dispatchPhase (/Users/Max/Documents/site-status/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:159:7)
    at XMLHttpRequest.EventTarget.dispatchEvent (/Users/Max/Documents/site-status/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:115:3)
    at XMLHttpRequest.DOM.EventTarget.dispatchEvent (/Users/Max/Documents/site-status/node_modules/zombie/lib/dom/jsdom_patches.js:155:31)
    at XMLHttpRequest._fire (/Users/Max/Documents/site-status/node_modules/zombie/lib/xhr.js:242:12)
    at XMLHttpRequest._stateChanged (/Users/Max/Documents/site-status/node_modules/zombie/lib/xhr.js:232:12)
    at null._onTimeout (/Users/Max/Documents/site-status/node_modules/zombie/lib/xhr.js:137:15)
    at Timer.listOnTimeout (timers.js:89:15)
```

A deeper inspection shows that this error is being thrown from eventloop.js :

```
// Window.clearTimeout
  clearTimeout(handle) {
    assert(this.queue, 'This browser has been destroyed');

    const timer = this.timers[handle];
    if (timer)
      timer.stop();
  }
```

A closer inspection shows that at the time this error is thrown, **this.queue** no longer exists. For whatever reason, the property just disappears. I don't know what to make of this. I'm not using mocha or another testing framework alongside zombie, but I don't think that matters. My exact process to run a test is:

- use zombie to go to the url I want to test
- use zombie to pull something from the DOM of the page it should have loaded
- check the value of what zombie pulled from the DOM and then call my callback
- go to the next test and repeat from step 1

**Comment by coyotte508** [comment]
I don't close tabs myself, and I don't do exactly as the OP, but I have the same problem although I don't destroy the browser myself.

**Comment by ohenepee** [comment]
I'm having the same issue when I try to download a big file then cancel it like this
```
    browser.on('response', (req, res) => {
      if (res.headers.get('Content-Type') == 'application/octet-stream') {
        console.log(res.headers.get('Content-Length'));
        res.destroy();
        browser.destroy()
      }
    })
```

`AssertionError: This browser has been destroyed... blah blah` pops up a few (20-30) seconds later

**Comment by pkantsedalov** [comment]
I have the same error when I have a loop of bunch of requests. 

After each loop I do the next:
```javascript
try {
    this._browser.destroy();
} catch(e){}

this.initBrowser();

// inside initBrowser()

```javascript
 this._browser = new Browser({
    silent: true
});
```

**Comment by uriel888** [comment]
Same error happened when loop almost same as OP

**Comment by jhenriquez** [comment]
**Disclaimer**: I'm not part of the zombie JS team, though I doubt there is such thing since it has not been updated in a while. I'm just browsing around the issues, because I just started using it. Anyways...

@mwiegant Bro, this is only a hunch but I'm inclined to believe that closing _all_ tabs is equivalent to closing (disposing/destroying) the browser, which doesn't mean the _browser object_ is nullified, in turn leading you to a point where you're trying to use an instance that is no longer valid. So, your first check: `brower = browser  ||  new Zombie();`  appears to be betraying you.

All this apart, if I may, allow me to suggest a different approach. Create a project that does these same steps, with your appropriate reactions and all, but don't have it run itself and let it die honorably every time instead. Then use an external tool (any cron scheduler or windows task, etc) to run it at your desired intervals. That way you won't have to deal with these Jon Snow madness, of killing and rebuilding complex objects.

Or... maybe try always instantiating the browser without checking it's falsyness, that could work too. But that one I don't guarantee :)
