### ISSUE TITLE
Problem in travis CI

### ISSUE THREAD

**Issue by angrykoala** [assaf/zombie#1036]
When executing my tests (mocha+zombiejs) in travis, the following error appears:

```
  Uncaught TypeError: Cannot read property 'replace' of undefined
      at findTargetPort (node_modules/zombie/lib/reroute.js:51:28)
      at Socket.Net.Socket.connect (node_modules/zombie/lib/reroute.js:69:18)
      at Socket.connect (net.js:862:37)
      at Socket.Net.Socket.connect (node_modules/zombie/lib/reroute.js:75:20)
      at ReqSocket.Socket.connect (node_modules/pm2-axon/lib/sockets/sock.js:295:8)
      at Object.launchRPC (node_modules/pm2/lib/Satan.js:456:26)
      at node_modules/pm2/lib/Satan.js:61:22
      at node_modules/pm2/lib/Satan.js:378:19
      at node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:452:19
      at Object.InteractorDaemonizer.getSetKeys (node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:359:19)
      at Object.InteractorDaemonizer.launchAndInteract (node_modules/pm2/lib/Interactor/InteractorDaemonizer.js:450:24)
      at ChildProcess.<anonymous> (node_modules/pm2/lib/Satan.js:375:26)
      at handleMessage (internal/child_process.js:718:10)
```

This error appears **before** the navigation tests, so it probably have something to do with browser configuration

``` js
var Browser = require('zombie');

Browser.localhost("127.0.0.1",3000);
```

All the navigation tests are passing (even in travis, after the error).

**Comment by demiurgosoft** [comment]
Instead of using `Browser.localhost`, using full URL in browser.visit works:
```js
browser.visit("http://127.0.0.1:3000",....
```

**Comment by fishcharlie** [comment]
This ever going to get addressed? For some reason I'm now having this same problem when testing locally.

**Comment by angrykoala** [comment]
Doesn't seem like that, ended up creating my own browser automation tool

**Comment by fishcharlie** [comment]
@angrykoala If it is open source and you have a link I’d love to check it out.

Very frustrating that this project is no longer maintained, and there is nothing in the README or notice that it’s no longer being maintained. I fully understand that priorities change, and due to open source mainly being free work it’s sometimes hard to continue to do it forever, but if it’s no longer being maintained, I don’t think it’s asking too much to put a notice in the README alerting people that it is no longer being maintained... @assaf

**Comment by angrykoala** [comment]
Feel free to check it @fishcharlie 
https://github.com/angrykoala/wendigo
