### ISSUE TITLE
AJAX with script tag in return - $(document).ready() firing too soon

### ISSUE THREAD

**Issue by david-ams** [assaf/zombie#1057]
I am using zombie.js in node.js to do some unit testing on a site. There are numerous ajax calls on my site, which typically return html and often script tags as well. I am getting errors on these ajax calls. Here is a sample which causes an error:

Parent page:
```
    <script src="jquery-1.11.1.js"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
    		var test = $.get('zombie2.htm', function(data){
    			$('#out').html(data);
    		});
    	});
    </script>
    <div id=out></div>
```
"zombie2.htm" page, loaded in the get:
```
    <script type="text/javascript">
    	$(document).ready(function fnZombie2Ready() {
    		var x = $('#divj').offset().top;
    	});
    </script>
    <div id="divj">asdf</div>
```
This page combination fails, giving the error: `TypeError: Cannot read property 'top' of undefined`. If I set a breakpoint in the function, I can see that the script tag is the only child element of `div#out`. The `#divj` has not been loaded yet. It seems like zombie.js is triggering the ready event too soon.

In experimenting, if I move the `script` tag after the `div` tag, it works fine. Oddly, it also works fine if I just remove the `type="text/javascript` from the `script` tag in `zombie2.htm`.

Here is the full debug log output:
```
< Tue, 28 Jun 2016 23:20:48 GMT zombie Opened window http://localhost/test/zombie1.htm 
< Tue, 28 Jun 2016 23:20:48 GMT zombie GET http://localhost/test/zombie1.htm => 200
< Tue, 28 Jun 2016 23:20:48 GMT zombie Loaded document http://localhost/test/zombie1.htm
< Tue, 28 Jun 2016 23:20:48 GMT zombie GET http://localhost/test/jquery-1.11.1.js => 200
< Tue, 28 Jun 2016 23:20:48 GMT zombie XHR readystatechange http://localhost/test/zombie2.htm
< Tue, 28 Jun 2016 23:20:48 GMT zombie XHR loadstart http://localhost/test/zombie2.htm
< Tue, 28 Jun 2016 23:20:48 GMT zombie GET http://localhost/test/zombie2.htm => 200
< Tue, 28 Jun 2016 23:20:48 GMT zombie XHR readystatechange http://localhost/test/zombie2.htm
< Tue, 28 Jun 2016 23:20:48 GMT zombie XHR readystatechange http://localhost/test/zombie2.htm
< Tue, 28 Jun 2016 23:20:48 GMT zombie TypeError: Cannot read property 'top' of undefined
<     at HTMLDocument.fnZombie2Ready (http://localhost/test/zombie1.htm:script:3:30)
<     at jQuery.Callbacks.fire (http://localhost/test/jquery-1.11.1.js:3119:30)
<     at Object.jQuery.Callbacks.self.add [as done] (http://localhost/test/jquery-1.11.1.js:3165:7)
<     at jQuery.fn.ready (http://localhost/test/jquery-1.11.1.js:3399:25)
<     at http://localhost/test/zombie1.htm:script:2:14
<     at Object.exports.runInContext (vm.js:44:17)
<     at window._evaluate (/home/user/www/node/node_modules/zombie/lib/document.js:253:75)
<     at Object.DOM.languageProcessors.javascript (/home/user/www/node/node_modules/zombie/lib/dom/scripts.js:26:12)
<     at define.proto._eval (/home/user/www/node/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:1477:47)
<     at executeInlineScript (/home/user/www/node/node_modules/zombie/lib/dom/scripts.js:67:14)
```

**Comment by david-ams** [comment]
it appears that this problem is actually with the jsdom plugin. Zombie's dependency is 5.3.0, but the github repo is up to 9.3.0, and has changed pretty drastically, so no chance of making this change over there.

Anyway, the problem is that the `.insertBefore` function acts recursively. So when it adds the ajax return to the DOM, it recurses and runs `.insertBefore` for every child node in the ajax return. And it also triggers `DOMNodeInserted` events after each child node is inserted. So if I added `console.log()` into my script tags in the ajax return, i could see that it was actually running the script twice! once as soon as the `script` tag was inserted during the recursive call, and again when the primary `.insertBefore` ran.

Here is a patch of the changes I made which seemed to fix the problem:
```
diff --git a/lib/jsdom/level1/core.js b/lib/jsdom/level1/core.js
index 5bd6a60..3991ec9 100644
--- a/lib/jsdom/level1/core.js
+++ b/lib/jsdom/level1/core.js
@@ -514,7 +514,7 @@ core.Node.prototype = {
       var tmpNode, i = newChild._childNodes.length;
       while (i-- > 0) {
         tmpNode = newChild.removeChild(newChild.firstChild);
-        this.insertBefore(tmpNode, refChild, true);
+        this.insertBefore(tmpNode, refChild);
       }
     } else if (newChild === refChild) {
       return newChild;
diff --git a/lib/jsdom/level2/events.js b/lib/jsdom/level2/events.js
index bf18c1f..9388833 100644
--- a/lib/jsdom/level2/events.js
+++ b/lib/jsdom/level2/events.js
@@ -167,13 +167,12 @@ function mutationEventsEnabled(el) {
 }
 
 var insertBefore_super = core.Node.prototype.insertBefore;
-core.Node.prototype.insertBefore = function(newChild, refChild, isRecursive) {
+core.Node.prototype.insertBefore = function(newChild, refChild) {
   var ret = insertBefore_super.apply(this, arguments);
   if (mutationEventsEnabled(this)) {
     var doc = getDocument(this),
         ev = doc.createEvent("MutationEvents");
 
-       if(isRecursive===true) return ret;
     ev.initMutationEvent("DOMNodeInserted", true, false, this, null, null, null, null);
     newChild.dispatchEvent(ev);
     if (this.nodeType == core.Node.DOCUMENT_NODE || this._attachedToDocument) {
user@UX302LA ~/www/node/node_modules/zombie/node_modules/jsdom $ 

```
