### ISSUE TITLE
error when visiting a page

### ISSUE THREAD

**Issue by chris74a** [assaf/zombie#1079]
Hello,

Firstly, thanks a lot for this excellent framework.

I run test on the my site, and I get this error:
1) "before all" hook
  0 passing (3s)
  1 failing

  1) form inspector "before all" hook:
     TypeError: Cannot set property 'aborted' of null
      at XMLHttpRequest.abort (node_modules\zombie\lib\xhr.js:57:23)
      at XMLHttpRequest.open (node_modules\zombie\lib\xhr.js:74:12)
      at ajax (https://localhost:44334/content/scripts/respond.js:298:8)
      at makeRequests (https://localhost:44334/content/scripts/respond.js:113:5)
      at https://localhost:44334/content/scripts/respond.js:116:6
      at XMLHttpRequest.req.onreadystatechange (https://localhost:44334//content/scripts/respond.js:303:5)
      at callListeners (node_modules\zombie\node_modules\jsdom\lib\jsdom\events\EventTarget.js:170:34)
      at dispatchPhase (node_modules\zombie\node_modules\jsdom\lib\jsdom\events\EventTarget.js:159:7)
      at XMLHttpRequest.EventTarget.dispatchEvent (node_modules\zombie\node_modules\jsdom\lib\jsdom\events\EventTarget.js:115:3)
      at XMLHttpRequest.DOM.EventTarget.dispatchEvent (node_modules\zombie\lib\dom\jsdom_patches.js:155:31)
      at XMLHttpRequest._fire (node_modules\zombie\lib\xhr.js:242:12)
      at XMLHttpRequest._stateChanged (node_modules\zombie\lib\xhr.js:232:12)
      at node_modules\zombie\lib\xhr.js:197:17
      at process._tickCallback (internal/process/next_tick.js:103:7)
      in https://localhost:44334/login

If I load the site in a browser, the script respond.js is loaded but nothing is run at respond.js:298.

Thanks a lot for your help!

**Comment by mdlavin** [comment]
@chris74a can you publish a copy of your site, or a smaller testcase, that reproduces the same behavior?

**Comment by juamedgod** [comment]
This may be the same issue I was reproducing:

#1097

**Comment by mdlavin** [comment]
I published a new version of zombie with fix #1097 . If you could re-test to see if you were affected by that it would be really helpful
