### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by mazieres** [assaf/zombie#1093]
After fresh install, [the basic example](https://github.com/assaf/zombie/blob/master/README.md#the-bite) shown in your readme doesn't work properly:

	$ node test.js
	/some/path/test.js:7
	describe('User visits signup page', function() {
	^

	ReferenceError: describe is not defined
	    at Object.<anonymous> (/Users/mazr/code/trendsapi/test.js:7:1)
	    at Module._compile (module.js:570:32)
	    at Object.Module._extensions..js (module.js:579:10)
	    at Module.load (module.js:487:32)
	    at tryModuleLoad (module.js:446:12)
	    at Function.Module._load (module.js:438:3)
	    at Module.runMain (module.js:604:10)
	    at run (bootstrap_node.js:394:7)
	    at startup (bootstrap_node.js:149:9)
	    at bootstrap_node.js:509:3

**Comment by mdlavin** [comment]
Just below that example, it says:
> This example uses the Mocha testing framework

A very common use case for Zombie is to be used in test automation and Mocha is a common test automation framework. If you run the example as a Mocha test, the `describe` function will be defined.
