### ISSUE TITLE
No open window with an HTML document

### ISSUE THREAD

**Issue by Foxhoundn** [assaf/zombie#1106]
Out of a sudden, we have started getting these errors on some of our tests - 

```
1) Scenario: Order detail page loads - features/order/order.feature:3
   Step: And "orders" get loaded - features/order/order.feature:5
   Step Definition: features/step_definitions/common_steps.js:137
   Message:
     AssertionError: No open window with an HTML document
         at Browser.query (/Users/filipwitosz/Code/Projects/qorus/node_modules/zombie-latest/lib/index.js:481:7)
         at World.check (world.js:225:24)
         at new Promise (/Users/filipwitosz/Code/Projects/qorus/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
         at World.waitForElement (world.js:238:12)
         at World.<anonymous> (common_steps.js:138:17)
         at nextTickCallbackWith0Args (node.js:420:9)
         at process._tickCallback (node.js:349:13)
```

I have seen the solution to increase the waitDuration, but it did not help at all.

```javascript
const options = {
      // eslint-disable-next-line
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
      waitDuration: 150 * 1000, <-
};
```

Anyone has any idea how to fix this? If I run the test separately with a @wip tag, it works fine.

We have 281 scenario and 1161 steps.
Any feedback appreciated, thanks!

**Comment by baccigalupi** [comment]
I got the same thing using a different implementation of cucumber. Any resolution that you could figure out @Foxhoundn?
