### ISSUE TITLE
Status Code 999 not in range

### ISSUE THREAD

**Issue by AurielleP** [assaf/zombie#1135]
Please add `999` to the status_code ranges -  HTTP/1.1 999 Request denied

**Comment by catcher-in-the-try** [comment]
Confirmed the problem. This exception cannot be caught using an `await browser.visit(...)` inside a `try/catch` and can only be caught using `process.on('uncaughtException')`. 

This happens, for example, when visiting LinkedIn pages. 

```
Visiting page https://www.linkedin.com/pub/dir/Name/Surname...
\node_modules\zombie\lib\fetch.js:346
      if (responseInit.status < 200 || responseInit.status > 599) throw new RangeError(`Status code ${responseInit.status} not in range`);
                                                                  ^

RangeError: Status code 999 not in range
    at new Response (\node_modules\zombie\lib\fetch.js:346:73)
    at Request.httpRequest.on.response (\node_modules\zombie\lib\pipeline.js:221:19)
    at Request.emit (events.js:182:13)
    at Request.onRequestResponse (\node_modules\request\request.js:1066:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Code:

Does not catch the exception:

```js
               try {
			const duration = 5000;
			await browser.visit(url, { duration });
		} catch (error) { 
                         // Does not reach this point
			console.log(error);
		}
```

Catches the exception:

```js
  process.on('uncaughtException', () => { console.log('UNCAUGHT'); });
```
