### ISSUE TITLE
Port != 8080 => this._ownerDocument.raise is not a function

### ISSUE THREAD

**Issue by xurei** [assaf/zombie#1165]
I'm trying to connect to localhost:8081 (or any other port != 8080).
I get this error : `TypeError: this._ownerDocument.raise is not a function`

With 8080, it works as expected.

See [this gist](https://gist.github.com/xurei/6b8071015716459ffd117c4e0d85fd3e) for a minimal example.

**Comment by ashlux** [comment]
I ran into the exact same thing when trying to upgrade from ~5.0.5 to 6.1.3.

We're using port 3000. However, when I switch to port 8080, I get the same issue.

```
     TypeError: this._ownerDocument.raise is not a function
         at XMLHttpRequest.raise (node_modules/zombie/lib/xhr.js:250:25)
         at _window._eventQueue.http (node_modules/zombie/lib/xhr.js:175:16)
         at enqueue (node_modules/zombie/lib/eventloop.js:237:11)
         at Immediate.<anonymous> (node_modules/zombie/lib/eventloop.js:503:11)
         at runCallback (timers.js:789:20)
         at tryOnImmediate (timers.js:751:5)
         at processImmediate [as _immediateCallback] (timers.js:722:5)
     From previous event:
         at Browser.wait (node_modules/zombie/lib/index.js:258:143)
         at lazyResolve (node_modules/zombie/lib/index.js:295:36)
         at Object.then (node_modules/zombie/lib/index.js:302:16)
         at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sergio-domingues** [comment]
Having the same issue when using browser.evaluate(jsCode)
