### ISSUE TITLE
File Protocol

### ISSUE THREAD

**Issue by nikgraf** [assaf/zombie#120]
Can't open local file …

```
zombie.visit('file:///Users/<path_to_file>/index.html', function (err, browser, status) {console.log(browser.html())})

Error: Cannot load resource: file:///Users/<path_to_file>/index.html
    at History.<anonymous> (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/history.js:46:15)
    at /usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/history.js:2:61
    at History.<anonymous> (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/history.js:33:16)
    at /usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/history.js:2:61
    at History._assign (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/history.js:157:14)
    at Browser.<anonymous> (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/browser.js:237:24)
    at /usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/browser.js:9:60
    at Browser.withOptions (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/browser.js:49:14)
    at Browser.visit (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/browser.js:236:12)
    at Object.visit (/usr/local/lib/node/.npm/zombie/0.9.4/package/lib/zombie/index.js:7:38)
```

**Comment by cellanda** [comment]
Did this issue return in 3.1.1?
I am getting a 404 for any file:// URL I try to visit

**Comment by cellanda** [comment]
and 4.0.10?
