### ISSUE TITLE
Cannot login into Facebook

### ISSUE THREAD

**Issue by vjeux** [assaf/zombie#167]
Hello,

I'm trying to login into Facebook with Zombie.js but it throws a `SyntaxError: Unexpected identifier` error in the process. I have carefully checked, I fill the good textboxes and press the good button.

Is there something that I missed or is something broken in Zombie.js?

Thanks!

``` javascript
var zombie = require("zombie");

var browser = new zombie.Browser({ debug: true });
browser.visit("http://www.facebook.com/", function(err, browser, status) {
    browser
        .fill('#email', 'christopher.chedeau@gmail.com')
        .fill('#pass', 'scrapeme') // The password is correct, I'll change it when the issue is fixed
        .pressButton('#login_form input[type=submit]', function(err, browser, status) {
            console.log(err.stack);
        });
});
```

```
Zombie: GET http://www.facebook.com/
Zombie: GET http://www.facebook.com/ => 200
Zombie: GET http://static.ak.fbcdn.net/rsrc.php/v1/yq/r/346Pl_u5ziA.js
Zombie: GET http://static.ak.fbcdn.net/rsrc.php/v1/yq/r/346Pl_u5ziA.js => 200
Zombie: Firing interval 1, interval: 20
error: Dispatching event 'submit' failed. - More:
[object Object]
error: Dispatching event 'submit' failed. - More:
[object Object]
Zombie: POST https://www.facebook.com/login.php?login_attempt=1
Zombie: GET http://www.facebook.com/
Zombie: GET http://www.facebook.com/ => 200
Zombie: GET http://static.ak.fbcdn.net/rsrc.php/v1/yq/r/346Pl_u5ziA.js
Zombie: GET http://static.ak.fbcdn.net/rsrc.php/v1/yq/r/346Pl_u5ziA.js => 200
SyntaxError: Unexpected identifier
    at Object.javascript (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:135:21)
    at Object._eval (/usr/local/lib/node/.npm/jsdom/0.2.4/package/lib/jsdom/level2/html.js:1282:46)
    at /usr/local/lib/node/.npm/jsdom/0.2.4/package/lib/jsdom/level2/html.js:44:20
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:100:11)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
    at Object.check (/usr/local/lib/node/.npm/zombie/0.10.0/package/lib/zombie/jsdom_patches.js:106:30)
Zombie: Firing interval 1, interval: 20
```

**Comment by pronebird** [comment]
I think it broke down recently, although FB's page looks the same.
