### ISSUE TITLE
requirejs shim deps not working in zombie

### ISSUE THREAD

**Issue by ShijunK** [assaf/zombie#555]
I am using cumber-js with zombie to test a web app. The web app itself uses requirejs to load Raphael and gRapael for vector graph. Everything works well in the browsers I tested (safari 6.0.5, firefox 20.0). However, when I run my cucumber feature to drive zombie browser, I got exception log from zombie "Raphael is not defined ReferenceError: Raphael is not defined".

```
Zombie: Opened window http://localhost:8080 
Zombie: GET http://localhost:8080/ => 200
Zombie: Loaded document http://localhost:8080/
Zombie: GET http://localhost:8080/js/plugins.js => 200
Zombie: GET http://localhost:8080/js/vendor/modernizr-2.6.2.min.js => 200
Zombie: GET http://localhost:8080/js/require.js => 200
Zombie: GET http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js => 200
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: GET http://localhost:8080/js/main.js => 200
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: Fired timeout after 4ms delay
Zombie: GET http://localhost:8080/js/lib/raphael.js => 200
Zombie: Fired timeout after 50ms delay
Zombie: GET http://localhost:8080/js/vendor/raphaeljs/g.raphael.js => 200
Raphael is not defined ReferenceError: Raphael is not defined
    at <anonymous>:26:1
```

Per the debug logging, it seems that Zombie honors the order of loading from requirejs (please see the dependency defined vis shim config below), however, the interpret and execution does not, the "g.raphael.js" seems be interpreted and executed before raphael.js. Though, it is only my guess. 

questions:
- does Zombie execute javascripts in the same order of loading?
- is there a way to make Zombie more verbose, i.e. tells the order of javascripts execution?

```
require.config({
    baseUrl: 'js/lib', //including raphael.js ver 2.1.0 
    paths: {
        "graphael": "../vendor/raphaeljs/g.raphael",
        "gbar": "../vendor/raphaeljs/g.bar",
        "gline": "../vendor/raphaeljs/g.line"
    },
    shim: {
        "graphael": {
            deps: ['raphael'],
            exports: 'gRaphael'
        },
        "gbar": {
            deps: ['graphael'],
            exports: 'gBar'
        },
        "gline": {
            deps: ['graphael'],
            exports: 'gLine'
        }
    }
});
```

**Comment by FoxxMD** [comment]
I am having the same problem except I am not using Raphael. I don't understand how @slickmb hack works around the problem. Could you please point me in the right direction?

```
Fri, 06 Feb 2015 16:50:09 GMT zombie GET https://thewebsite.example/WijmoScripts?v=7Mx9q_fJhaLN1H0WRKzbPXyM_63VPPRTlzzKJghHwWs1 => 200
{ [TypeError: Cannot read property 'svg' of undefined] filename: undefined }
Fri, 06 Feb 2015 16:50:09 GMT zombie Cannot read property 'svg' of undefined TypeError: Cannot read property 'svg' of undefined
    at <anonymous>:1:65965
    in https://thewebsite.example/
Fri, 06 Feb 2015 16:50:09 GMT zombie Object [object Object] has no method 'wijdialog' TypeError: Object [object Object] has no method 'wijdialog'
    at HTMLDocument.<anonymous> (<anonymous>:1:231039)
    at i.Callbacks.a (<anonymous>:1:111390)
    at Object.i.Callbacks.h.fireWith [as resolveWith] (<anonymous>:1:112190)
    at Function.i.extend.ready (<anonymous>:1:107031)
    at HTMLDocument.h (<anonymous>:1:104426)
    at callListeners (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:207:38)
    at dispatchPhase (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:196:13)
    at HTMLDocument.events.EventTarget.dispatchEvent (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:294:9)
    at HTMLDocument.Events.EventTarget.dispatchEvent (/Users/auser/Coding/myapp/node_modules/zombie/lib/zombie/window.js:524:31)
    at HTMLDocument.inheritFrom.close (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:476:12)
    in https://thewebsite.example/
[TypeError: Object [object Object] has no method 'wijdialog']
Fri, 06 Feb 2015 16:50:09 GMT zombie Event loop is empty

/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:658
            throw e;
                  ^
Error: TypeError: Cannot read property 'svg' of undefined
    at Object.ret.isClass [as ensureErrorObject] (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/util.js:229:20)
    at Promise.module.exports.Promise._rejectCallback (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:444:22)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:489:17)
    at Promise.module.exports.Promise._settlePromiseAt (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:562:18)
    at Promise.module.exports.Promise._settlePromises (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:678:14)
    at Async._drainQueue (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:89:10)
    at drainQueues (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickDomainCallback (node.js:486:13)

Process finished with exit code 8
```

Thank you!

**Comment by xiaoshao** [comment]
I have the same problem. How to fix this?
