### ISSUE TITLE
html body gets executed as javascript, throws error

### ISSUE THREAD

**Issue by ximonn** [assaf/zombie#558]
version: 2.0.0-alpha19

for https://www.shopaunt.com/en/register.html, I got an error parsing the webpage, resulting in the zombie script crashing:

Unexpected token < SyntaxError: Unexpected token <
    at Contextify.sandbox.run (/usr/local/lib/node_modules/zombie/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
    at Object.window._evaluate (/usr/local/lib/node_modules/zombie/lib/zombie/window.js:189:25)
    at Object.HTML.languageProcessors.javascript (/usr/local/lib/node_modules/zombie/lib/zombie/scripts.js:25:21)
    at Object.define.proto._eval (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:1458:47)
    at Object.loaded (/usr/local/lib/node_modules/zombie/lib/zombie/scripts.js:78:23)
    at /usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:73:20
    at Object.item.check (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:339:11)
    at /usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:357:12
    at /usr/local/lib/node_modules/zombie/lib/zombie/eventloop.js:245:18
    at Object._onImmediate (/usr/local/lib/node_modules/zombie/lib/zombie/eventloop.js:146:11)

Looking into it a bit, it seems that the method which evaluates bits of javascripts, tries to evaluate html code as if its javascript.
To get past that I used the following 
workaround, in /node_modules/zombie/lib/zombie/scripts.js line 20:

 if (code && !code.match(/^\s*</)) {

so any code starting with '<' would not be evaluated.

regards,
Simon

**Comment by TheFive** [comment]
Just to help anyone with the same error.
I use a local copy of Bootstrap that is not checked in, so the bootstrap files (javascript) are missing, this explains the error.
