### ISSUE TITLE
Zombie is not working with node 0.8.26

### ISSUE THREAD

**Issue by Almad** [assaf/zombie#600]
```
zombie = require 'zombie'

b = new zombie.Browser()
b.visit "https://google.com"

TypeError: Parameter 'url' must be a string, not object
    at Object.urlParse [as parse] (url.js:94:11)
    at Resources._makeRequest (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/resources.js:172:15)
    at Resources.request (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/resources.js:145:20)
    at EventLoop.perform (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/eventloop.js:141:5)
    at Resources.request (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/resources.js:144:37)
    at History._resource (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/history.js:117:40)
    at History._pageChanged (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/history.js:78:19)
    at History._assign (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/history.js:271:17)
    at Browser.visit (/Users/almad/Documents/projects/apiary/node_modules/zombie/lib/zombie/browser.js:336:25)
    at repl:1:7
    at REPLServer.replDefaults.eval (/Users/almad/.nvm/v0.8.26/lib/node_modules/coffee-script/lib/coffee-script/repl.js:33:28)
    at repl.js:248:12
    at Interface.inputStream.on.multiline.enabled (/Users/almad/.nvm/v0.8.26/lib/node_modules/coffee-script/lib/coffee-script/repl.js:62:9)
    at Interface.EventEmitter.emit (events.js:126:20)
    at Interface._onLine (readline.js:200:10)
    at Interface._line (readline.js:518:8)
    at Interface._ttyWrite (readline.js:736:14)
    at ReadStream.onkeypress (readline.js:97:10)
    at ReadStream.EventEmitter.emit (events.js:126:20)
    at emitKey (readline.js:1058:12)
    at ReadStream.onData (readline.js:807:7)
    at ReadStream.EventEmitter.emit (events.js:96:17)
    at TTY.onread (net.js:397:14)
```

**Comment by ntlk** [comment]
I am also having this issue, using zombie 1.4.1 with node 0.9.12.

**Comment by jcollum-hcg** [comment]
@ntlk I hope the fix is pretty clear to you.

**Comment by capaj** [comment]
@assaf I am still getting this when I do:
```
const Browser = require('zombie')

// We're going to make requests to http://example.com/signup
// Which will be routed to our test server localhost:3000
Browser.localhost('example.com', 8090)

describe('User visits landing page', function() {

  const browser = new Browser()

  before(function() {
    return browser.visit('/')
  })

  describe('submits form', function() {

    it('should be successful', function() {
      browser.assert.success()
    })
  })

})
```
