### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'compareDocumentPosition' in null

### ISSUE THREAD

**Issue by demian85** [assaf/zombie#836]
I'm trying to build a 'web previewer' that visits a specified URL and obtains a title, image and description.

While visiting facebook.com, for example...

```
/home/demian/www/web-preview/node_modules/zombie/node_modules/bluebird/js/main/async.js:103
                throw res.e;
                         ^
TypeError: Cannot use 'in' operator to search for 'compareDocumentPosition' in null
    at /home/demian/www/web-preview/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:267:43
    at module.exports (/home/demian/www/web-preview/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:37:7)
    at addNwmatcher (/home/demian/www/web-preview/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:6:27)
    at HTMLDocument.<anonymous> (/home/demian/www/web-preview/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:14:12)
    at HTMLDocument.querySelector (/home/demian/www/web-preview/node_modules/zombie/node_modules/jsdom/lib/jsdom/level1/core.js:63:53)
    at /home/demian/www/web-preview/lib/scraper.js:12:15
    at tryCatch1 (/home/demian/www/web-preview/node_modules/zombie/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/home/demian/www/web-preview/node_modules/zombie/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/home/demian/www/web-preview/node_modules/zombie/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/home/demian/www/web-preview/node_modules/zombie/node_modules/bluebird/js/main/promise.js:733:18)
```

I know zombie is just for testing, but this is a programming error in the library and has nothing to do with Facebook.

**Comment by dperini** [comment]
Based on past reports in both ´nwmatcher´ and ´jsdom´ I believe this may be due to a document missing the root HTML element (documentElement), which is mandatory for a DOM selector engine.

Have a look here (nwmatcher): https://github.com/dperini/nwmatcher/pull/83

and also here (jsdom): https://github.com/tmpvar/jsdom/issues/555

Hope these links can help fix it.
