### ISSUE TITLE
Error while using browser.resources.fail

### ISSUE THREAD

**Issue by makbol** [assaf/zombie#840]
I'm trying to test my frontend script with zombie.js which sends xhr to external server. In other tests I'm using `browser.resources.mock` which works fine but i was going to test what if timeout will be reach or external server will be dead.

My code:

```javascript
it('should fail gracefully when external server is disabled', function(done){

  browser.resources.fail('http://localhost:3000/api');
  browser.resources.mock('http://localhost:3000/api', {
   statusCode: 200,
   headers:    { 'ContentType': 'application/json' },
   body:       apiResponse1
  });

  browser.visit('http://localhost:3000')
    .then(function() {
      // sth here
      done();
    });
});
```

What I've got is:
```
Possibly unhandled Error: This request was intended to fail
    at failTheRequest (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:102:19)
    at Browser.Resources.specialURLHandlers (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:378:7)
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:212:28
    at Browser.Resources.createBody (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:364:3)
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:212:28
    at Browser.Resources.mergeHeaders (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:305:3)
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:212:28
    at Browser.Resources.normalizeURL (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:279:3)
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:212:28
    at Resources.runPipeline (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:243:5)
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:64:22
    at tryCatch2 (/Users/max/repos/abt-script/node_modules/zombie/node_modules/bluebird/js/main/util.js:29:21)
    at Promise._resolveFromResolver (/Users/max/repos/abt-script/node_modules/zombie/node_modules/bluebird/js/main/promise.js:562:13)
    at new Promise (/Users/max/repos/abt-script/node_modules/zombie/node_modules/bluebird/js/main/promise.js:58:37)
    at Resources.request (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/resources.js:62:15)
    at EventQueue.http (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/eventloop.js:256:28)
    at XMLHttpRequest.send (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/xhr.js:117:30)
    at Abt.sendRequest (<anonymous>:57:11)
    at Abt.init (<anonymous>:21:8)
    at abtScript (<anonymous>:154:7)
    at <anonymous>:158:3
    at Contextify.sandbox.run (/Users/max/repos/abt-script/node_modules/zombie/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
    at DOMWindow.window._evaluate (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/window.js:210:25)
    at Object.HTML.languageProcessors.javascript (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/scripts.js:27:21)
    at define.proto._eval (/Users/max/repos/abt-script/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:1675:47)
    at loaded (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/scripts.js:76:23)
    at /Users/max/repos/abt-script/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:89:20
    at Object.item.check (/Users/max/repos/abt-script/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:361:11)
    at /Users/max/repos/abt-script/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:379:12
    at /Users/max/repos/abt-script/node_modules/zombie/lib/zombie/eventloop.js:263:13
    at Object._onImmediate (/Users/max/repos/abt-script/node_modules/zombie/lib/zombie/eventloop.js:161:15)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

When `browser.resources.fail` is after `browser.resources.mock` then nothing happens, works fine, just like without `browser.resources.fail`

**Comment by assaf** [comment]
If you tell the resource to fail every request, it will fail every request, just as expected.
