### ISSUE TITLE
Cannot ready property 'svg' of undefined

### ISSUE THREAD

**Issue by FoxxMD** [assaf/zombie#852]
I am having the same problem [as this issue](https://github.com/assaf/zombie/issues/555) except I am not using Raphael. I don't understand how @slickmb hack works around the problem. Could you please point me in the right direction?

I am using vanilla code, just attempting to run with node

```
var Browser = require('zombie');

// Set base url for easy clock
Browser.localhost('https://thewebsite.example',80);
Browser.strictSSL = true;
Browser.runScripts = false;
Browser.loadCSS = false;

//Load the page
var browser = Browser.create();

//log error and info
browser.on('error', function(error){
    console.error(error);
});

browser.visit('/').then(function(){ //erroring here
    //Ensure we are on the login page
    browser.console('info', 'Looking for login elements...');
    browser.assert.element('#login input#Username');
    browser.assert.element('#login input#Password');
//code continues..
```

```
Fri, 06 Feb 2015 16:50:09 GMT zombie GET https://thewebsite.example/WijmoScripts?v=7Mx9q_fJhaLN1H0WRKzbPXyM_63VPPRTlzzKJghHwWs1 => 200
{ [TypeError: Cannot read property 'svg' of undefined] filename: undefined }
Fri, 06 Feb 2015 16:50:09 GMT zombie Cannot read property 'svg' of undefined TypeError: Cannot read property 'svg' of undefined
    at <anonymous>:1:65965
    in https://thewebsite.example/
Fri, 06 Feb 2015 16:50:09 GMT zombie Object [object Object] has no method 'wijdialog' TypeError: Object [object Object] has no method 'wijdialog'
    at HTMLDocument.<anonymous> (<anonymous>:1:231039)
    at i.Callbacks.a (<anonymous>:1:111390)
    at Object.i.Callbacks.h.fireWith [as resolveWith] (<anonymous>:1:112190)
    at Function.i.extend.ready (<anonymous>:1:107031)
    at HTMLDocument.h (<anonymous>:1:104426)
    at callListeners (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:207:38)
    at dispatchPhase (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:196:13)
    at HTMLDocument.events.EventTarget.dispatchEvent (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/events.js:294:9)
    at HTMLDocument.Events.EventTarget.dispatchEvent (/Users/auser/Coding/myapp/node_modules/zombie/lib/zombie/window.js:524:31)
    at HTMLDocument.inheritFrom.close (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:476:12)
    in https://thewebsite.example/
[TypeError: Object [object Object] has no method 'wijdialog']
Fri, 06 Feb 2015 16:50:09 GMT zombie Event loop is empty

/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:658
            throw e;
                  ^
Error: TypeError: Cannot read property 'svg' of undefined
    at Object.ret.isClass [as ensureErrorObject] (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/util.js:229:20)
    at Promise.module.exports.Promise._rejectCallback (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:444:22)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:489:17)
    at Promise.module.exports.Promise._settlePromiseAt (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:562:18)
    at Promise.module.exports.Promise._settlePromises (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/promise.js:678:14)
    at Async._drainQueue (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:89:10)
    at drainQueues (/Users/auser/Coding/myapp/node_modules/zombie/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickDomainCallback (node.js:486:13)

Process finished with exit code 8
```

Thank you!

**Comment by slickmb** [comment]
My hack from #555 no longer works with the latest version of Zombie...  It worked originally because Raphael makes its decision about using vml or svg based partially on the existence of the SVGAngle property on the document window.  It seems that my technique for adding the SVGAngle property to the document window is no longer working with the latest version.  I haven't had a chance to look for a new approach.
