### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kabriel** [assaf/zombie#884]
Just upgraded to v3.1.0 from v2.5.1 and I'm getting a RangeError.

```
  zombie RangeError: Maximum call stack size exceeded
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:48:57)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50)
    at DOM.HTMLFrameElement._attrModified (/project/node_modules/zombie/lib/dom/iframe.js:94:50) +4ms
Error: { [RangeError: Maximum call stack size exceeded] filename: undefined }
```

Not doing anything special, just trying to load the main page.

```
var Zombie = require('zombie')
Zombie.visit('https://www.flawk.to/', function(err) {
  if (err) {
    console.log('Error:', err)
  } else {
    console.log('Ready')
  }
})
```

**Comment by paton** [comment]
I'm also getting this issue in v3.1 using the same requesting https://localizejs.com/

Downgrading to 2.5 fixes this.

**Comment by paton** [comment]
Not sure if this helps, but running the script with `--stack-size=10000` causes a seg fault, rather than the usual

    [Error: Maximum call stack size exceeded]

**Comment by ibash** [comment]
Same thing, I think there is a typo in the iframe file. Try this diff:
```
diff --git a/node_modules/zombie/lib/dom/iframe.js b/node_modules/zombie/lib/dom/iframe.js
index bd58721..61ecbd4 100644
--- a/node_modules/zombie/lib/dom/iframe.js
+++ b/node_modules/zombie/lib/dom/iframe.js
@@ -46,6 +46,8 @@ DOM.HTMLFrameElement.prototype.setAttribute = function (name, value) {
 };

 DOM.HTMLFrameElement.prototype._attrModified = function (name, value, oldValue) {
+  DOM.HTMLElement.prototype._attrModified.call(this, name, value, oldValue);
+
   var _this = this;

   var iframe = this;
@@ -85,6 +87,6 @@ DOM.HTMLFrameElement.prototype._attrModified = function (name, value, oldValue)
     parentWindow.__defineGetter__(windowName, function () {
       return _this.contentWindow;
     });
-  } else DOM.HTMLFrameElement.prototype._attrModified.call(this, name, value, oldValue);
+  }
 };
```
