### ISSUE TITLE
browser.dump() fails on Cookies section

### ISSUE THREAD

**Issue by rmfitzpatrick** [assaf/zombie#887]
In zombie 3.1.0, I see the following when calling browser.dump():
````
Cookies:

/home/fvm/tmp/zombie/node_modules/zombie/node_modules/babel-runtime/core-js.js:550
  return assertObject(getIter.call(it));
                              ^
TypeError: Cannot call method 'call' of undefined
    at Function.getIterator (/home/fvm/tmp/zombie/node_modules/zombie/node_modules/babel-runtime/core-js.js:550:31)
    at Cookies.dump (/home/fvm/tmp/zombie/node_modules/zombie/lib/cookies.js:37:149)
    at Browser.dump (/home/fvm/tmp/zombie/node_modules/zombie/lib/index.js:1348:18)
    at Object.<anonymous> (/home/fvm/tmp/zombie/test.js:52:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3````

I have made no attempt to get or set cookies in this script.

**Comment by rmfitzpatrick** [comment]
This was caused user error (calling dump() at inappropriate time).
