### ISSUE TITLE
Zombiejs can't process the the website js code correctly

### ISSUE THREAD

**Issue by freewind** [assaf/zombie#907]
```
browser.visit("https://www.realestate.com.au/my-real-estate/my-profile/")
```

It will show:

```
  zombie Opened window https://www.realestate.com.au/my-real-estate/my-profile/  +0ms
  zombie GET https://www.realestate.com.au/my-real-estate/my-profile/ => 200 +2s
  zombie Loaded document https://www.realestate.com.au/my-real-estate/my-profile/ +128ms
  zombie GET https://www.realestate.com.au/assets/js/lib/analytics/s_code.js => 200 +532ms
  zombie GET https://www.realestate.com.au/my-real-estate/my-profile/js/lib/requirejs-176c850cebecfd8d4ea8de0b5c3f32d7.js => 200 +6ms
  zombie GET https://www.realestate.com.au/assets/js/lib/analytics/v60.js => 200 +8ms
  zombie GET https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js => 200 +352ms
  zombie Fired setTimeout after 4ms delay +85ms
  zombie Fired setTimeout after 4ms delay +2ms
  zombie Fired setTimeout after 4ms delay +4ms
  zombie Fired setTimeout after 50ms delay +51ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +52ms
  zombie Fired setTimeout after 50ms delay +52ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +56ms
  zombie Fired setTimeout after 50ms delay +50ms
  zombie Fired setTimeout after 50ms delay +51ms
  zombie Fired setTimeout after 50ms delay +53ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +54ms
  zombie Fired setTimeout after 50ms delay +52ms
  zombie Fired setTimeout after 50ms delay +52ms
  zombie Fired setTimeout after 50ms delay +50ms
  zombie Fired setTimeout after 50ms delay +51ms
  zombie Fired setTimeout after 50ms delay +53ms
  zombie Fired setTimeout after 50ms delay +49ms
  zombie Fired setTimeout after 50ms delay +55ms
  zombie GET https://www.realestate.com.au/my-real-estate/my-profile/js/mainApp-ad26cf886135b2e699ba2b9c09f19344.js => 200 +24ms
  zombie Fired setTimeout after 50ms delay +29ms
  zombie GET https://www.adobetag.com/d2/reagroup/live/realestatecomau20.js => 200 +21ms
  zombie TypeError: undefined is not a function
    at https://www.adobetag.com/d2/reagroup/live/realestatecomau20.js:740:3
    in https://www.realestate.com.au/my-real-estate/my-profile/ +7ms
```

It show an error: `TypeError: undefined is not a function` at `https://www.adobetag.com/d2/reagroup/live/realestatecomau20.js:740:3`

But if I open https://www.realestate.com.au/my-real-estate/my-profile/  from chrome, it doesn't show any error.

I'm not sure where is wrong, and how to make a workaround.

**Comment by assaf** [comment]
FYI Zombie is not designed for scraping web sites.

**Comment by freewind** [comment]
Sorry, not sure what does `scraping web sites` mean.

I want to write some e2e testings, to verify:

1. when I visit that url, it will redirect to another login page since I'm not logged in
2. when it redirects to login page, the login form will be shown

Since both functionalities are implemented with js code, I can't find a way to test it if the referenced js code broken.

Doesn't zombie fit my requirement, I was thinking zombie is the right tool? When is the right time?

**Comment by dshadowwolf** [comment]
I am seeing a similar error when trying to use Zombie to test modifications to javascript backing the front-end of a MediaWiki based site I work as the chief developer/admin for. When I just pull in the 'Main Page' URL of the site to test the code, it doesn't even get to what I wanted to test.

[Error: http://shifti.org/load.php?debug=false&lang=en&modules=site&only=scripts&skin=shiftinew&*:1
mw.loader.state({"site":"ready"});
^
mw is not defined]

ie: It dies inside code that works fine in a browser. From what I can tell, zombie is supposed to be targeted at testing websites. Is this not correct ?
