### ISSUE TITLE
visiting file schema URLs return 404

### ISSUE THREAD

**Issue by cellanda** [assaf/zombie#915]
I see this has been an issue in the past and I think it has come back. Well, at least on windows 7.

With code such as:
        var url = encodeURI('file://c:/somefile.html');
        browser.visit(url).catch(function () {}).then(function () {
            console.log('href: ' + browser.location.href);
            console.log(browser.statusCode);
        });

I get:
href: file:///c:/somefile.html
404

And it does not load the file.

**Comment by cellanda** [comment]
This is what the tail of the tests look like for me on Windows 7:
.
.
684 passing (41s)
12 pending
6 failing

1) Forms file upload with JS should know file size:

    AssertionError: '13' deepEqual '12'
    + expected - actual

    +"12"
    -"13"

    at assertMatch (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/assert.js:16:12)
    at Assert.text (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/assert.js:204:5)
    at Context.<anonymous> (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/test/forms_test.js:1303:22)

2) Google map should load map:
   AssertionError: undefined == true
    at Context.<anonymous> (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/test/google_map_test.js:36:5)

3) Google map should set bounds:
   TypeError: Cannot read property 'getBounds' of undefined
    at Context.<anonymous> (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/test/google_map_test.js:39:38)

4) History location open from file system "before all" hook:
   Error: Server returned status code 404 from file:///y:/%5CTerry%5CStuff%5CDevelopment%5CSoftware%5CGitHub%5Cassaf%5Czombie%5Ctest/data/index.html
    at callee$1$0$ (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/document.js:573:13)
From previous event:
    at Browser.wait (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:288:61)
    at lazyResolve (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:329:24)
    at Object.then (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:336:16)

5) Scripts file:// uri scheme "before all" hook:
   Error: Server returned status code 404 from file:///y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/test/data/file_scheme.html
    at callee$1$0$ (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/document.js:573:13)
From previous event:
    at Browser.wait (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:288:61)
    at lazyResolve (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:329:24)
    at Object.then (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:336:16)

6) Scripts file:// uri with encoded spaces "before all" hook:
   Error: Server returned status code 404 from file:///y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/test/data/dir%20with%20spaces/file_scheme%20with%20spaces.html
    at callee$1$0$ (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/document.js:573:13)
From previous event:
    at Browser.wait (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:288:61)
    at lazyResolve (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:329:24)
    at Object.then (y:/Terry/Stuff/Development/Software/GitHub/assaf/zombie/src/index.js:336:16)

**Comment by the-t-in-rtf** [comment]
We can only use the 2.x and parts of the 3.x line as we are using node <= 12, but I can verify that the file:// tests fail for Windows 8.1 for all of the 3.x tags.

**Comment by the-t-in-rtf** [comment]
We are working around this at the moment by hosting content to be tested using express.js and its static router module.
