### ISSUE TITLE
Use of const and and let in strict mode.

### ISSUE THREAD

**Issue by willgdjones** [assaf/zombie#916]
Relatively new issue creator here.

With the line `const Browser = require('zombie');`  I'm getting: 
`~/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/living/parent-node.js:3
const defineGetter = require("../utils").defineGetter;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/living/index.js:25:1)`

Seems like [this post](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode) might be a fix. Changing all the `const` and `let` I find to `var` is a quick workaround for me.

Is this repeatable or just for me?

Thanks,

Will

**Comment by assaf** [comment]
Zombie doesn't work on Node, please use io.js.

**Comment by willgdjones** [comment]
Thanks for the quick reply, ideally I'd like to stick with Node. I'm guessing Zombie 3x won't have this issue?

**Comment by assaf** [comment]
No guarantees

**Comment by willgdjones** [comment]
Fair - thanks!

**Comment by jereme-leandev** [comment]
Just encountered this error. Good to know that it requires io.js instead. Should have read the instructions :smiley:
