### ISSUE TITLE
Zombie 4.0.11 fails to visit a URL (any URL with resources, so it seems)

### ISSUE THREAD

**Issue by yaronassa** [assaf/zombie#926]
When working with debug(), I get this output:
Sun, 14 Jun 2015 08:43:26 GMT zombie Resource error TypeError: Cannot set property 'time' of undefined
    at Pipeline._fetch$ (c:\Dev\projects\MyProj\node_modules\zombie\lib\pipeline.js:89:27)
    at tryCatch (c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\regenerator\runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\regenerator\runtime.js:165:16
    at run (c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
    at c:\Dev\projects\MyProj\node_modules\zombie\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Reverting to @4.0.10 solves the problem.

**Comment by NaxYo** [comment]
Same here! +1

**Comment by yaronassa** [comment]
(I'm on Win8.1_64bit, with node 0.12.2; But also tested it with io.js 2.2 to make sure it wasn't node)

**Comment by superboum** [comment]
Same problem :

```
  zombie Resource error +9ms TypeError: Cannot set property 'time' of undefined
    at Pipeline._fetch$ (/my/project/node_modules/zombie/lib/pipeline.js:90:27)
    at tryCatch (/my/project/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/my/project/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/my/project/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/my/project/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at /my/project/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at run (/my/project/node_modules/zombie/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /my/project/node_modules/zombie/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickCallback (node.js:355:11)
```

(Fedore 22, node v0.12.4)

**Comment by JaviDev** [comment]
Same on debian, latest iojs and zombie.

**Comment by dynamite-ready** [comment]
Confirmed on Windows 7, NodeJS v0.12.4.
Very frustrating bug to launch with.

Thank you for the help, yaronassa.

**Comment by PavelVanecek** [comment]
Same (or similar) problem:

```
 TypeError: Cannot set property 'time' of undefined
        at Pipeline._fetch$ (/usr/local/lib/node_modules/zombie/lib/pipeline.js:100:19)
        at tryCatch (/usr/local/lib/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:67:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:297:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:100:21)
        at invoke (/usr/local/lib/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:136:37)
        at bound (domain.js:254:14)
        at runBound (domain.js:267:12)
        at /usr/local/lib/node_modules/zombie/node_modules/babel-runtime/regenerator/runtime.js:168:16
        at run (/usr/local/lib/node_modules/zombie/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
        at /usr/local/lib/node_modules/zombie/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
        at doNTCallback0 (node.js:408:9)
        at process._tickDomainCallback (node.js:378:13)
        at Function.Module.runMain (module.js:469:11)
        at startup (node.js:117:18)
        at node.js:946:3
```

Using [iojs image](https://github.com/nodejs/docker-iojs)

    node --version
    $ v2.2.1
    npm --version
    2.11.0
    npm list | grep zombie
    └─┬ zombie@4.0.11

**Comment by xlilien** [comment]
Same here, thanks a lot for reporting!

**Comment by yaronassa** [comment]
Version 4.0.12 resolved the issue.
Thanks.
