### ISSUE TITLE
Zombie on Openshift

### ISSUE THREAD

**Issue by reyy** [assaf/zombie#941]
Hi,

I am trying to deploy my zombie 2.51 node.js app on Openshift and it appears that the callback function gets triggered before the page is loaded, resulting in an exception. It is working fine locally and on a VM server, and the error appears to only occur in Openshift?

    var url = "https://mylogin.page";
    var browser = new Browser();
    var username = req.body.username;
    var password = req.body.password;

    browser.open();
    browser.visit(url, function(err) {
        browser
        .fill('input[name="txtUserID"]', username)
        .fill('input[name="txtPwd"]', password)
        .pressButton('input[value="Login"]', function(response) { /*next_page*/});
    });

>Possibly unhandled TypeError: Cannot use 'in' operator to search for 'compareDocumentPosition' in null
    at /var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:267:43
    at module.exports (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:37:7)
    at addNwmatcher (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:6:27)
    at HTMLDocument.<anonymous> (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:18:29)
    at HTMLDocument.querySelectorAll (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/node_modules/jsdom/lib/jsdom/level1/core.js:63:53)
    at Browser.queryAll (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/lib/zombie/browser.js:348:26)
    at Browser.field (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/lib/zombie/browser.js:591:17)
    at Browser._findOption (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/lib/zombie/browser.js:662:18)
    at Browser.select (/var/lib/openshift/[app-id]/app-root/runtime/repo/node_modules/zombie/lib/zombie/browser.js:692:19)

Just wondering if anybody else has encountered this or has a fix? Thanks!

**Comment by demiurgosoft** [comment]
Late, but found this: <http://www.e-howtogeek.com/51357/openshift-zombiejs>

**Comment by northcott-j** [comment]
Wondering if either of you figured this out. I followed the link, but it seems like browser.coffee is missing or moved, so I can't see the relevant code lines. Using just new Browser(), I get a Proxy 503 response. Using the Openshift NodeJS IP env variable, I get AssertionError: No open window with an HTML document. Thanks for the help!
