### ISSUE TITLE
Can't get this simple script to work!

### ISSUE THREAD

**Issue by sawteeth** [assaf/zombie#943]
```js
var Zombie = require('zombie');
 
var zombie = new Zombie({
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
    debug: true,
    waitFor: 10000
});
 
var url = 'https://google.com';
 
zombie.visit(url, function(err, browser) {
    console.log("Currently visiting " + browser.location);
});
```

Errors:
> project/node_modules/zombie/node_modules/bluebird/js/main/promise.js:673
            throw e;
                  ^
TypeError: Cannot read property 'location' of undefined
    at project/parser/tasks/directory.js:13:48
    at tryCatcher (project/node_modules/zombie/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (project/node_modules/zombie/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (project/node_modules/zombie/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (project/node_modules/zombie/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (project/node_modules/zombie/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (project/node_modules/zombie/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

I'm using Node.js 0.12.0, and Zombie 2.5.1.  Any help appreciated, thanks!

**Comment by cobbdb** [comment]
I'm not sure what all those other options are for, but this works for me:
```javascript
var Browser = require('zombie');
Browser.visit('http://google.com', function (err, browser) {
    console.log('Currently visiting ' + browser.location);
});
```
