### ISSUE TITLE
AssertionError: No open window with an HTML document

### ISSUE THREAD

**Issue by rahul-desai3** [assaf/zombie#953]
While I was crawling & scrapping http://www.mesotheliomagroup.com/ completely, my script terminated with an error while scrapping this particular webpage: http://www.mesotheliomagroup.com/treatment/chemotherapy/drugs/carboplatin#side-effects

It had crawled and scrapped 63% of all the pages by that time.

Here is the error that I got:

```
/Users/rahuldesai/nightmare/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^
AssertionError: No open window with an HTML document
    at Browser.queryAll (/Users/rahuldesai/nightmare/node_modules/zombie/lib/index.js:460:7)
    at /Users/rahuldesai/nightmare/index.js:67:20
    at done (/Users/rahuldesai/nightmare/node_modules/zombie/lib/eventloop.js:589:11)
    at timeout (/Users/rahuldesai/nightmare/node_modules/zombie/lib/eventloop.js:601:33)
    at Timer.listOnTimeout (timers.js:89:15)
```

Here is what my code looks like:

```
const Browser = require('zombie');  // to grab the HTML from URL
var Url = require("url");  // for parsing URLs

var emailAddresses = [], 
	links = [], 
	seen = [],
	errors = [],
	index = 0;

const browser = new Browser();

var testDomain = 'http://www.mesotheliomagroup.com/';

links.push(testDomain);  // just to start with


function scrapAndCrawl(links){
	var testLink = links[index];

	console.log('Crawling page # ' + index);
	console.log('Total links = ' + links.length);
	console.log((links.length - index) + ' more link(s) to crawl.');
	console.log('*** PROGRESS = ' + Math.floor(index/links.length*100) + ' %');
	console.log('Email addresses found so far: ', emailAddresses);
	console.log('Now Crawling: ' + testLink);

	if(!seen[testLink]){
		// get HTML
		browser.visit(testLink, function() {

			seen[testLink] = true;

			var htmlString = browser.html();

			// filter all <a>'s
			var a = browser.queryAll("a").map(function (node) {

				var href = node.href;

				if(href){

					href = href.trim();

					href = Url.resolve(testLink, href);
					
					if(href.indexOf(testDomain) === 0 && // href has testDomain in it
						/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi.test(href) === false && // href is not an email
						links.indexOf(href) === -1 &&  // not in links yet
						!seen[href]){  // href is not seen yet

							// console.log('Found an eligible and unique link: ' + href);
							links.push(href);

							newLinksNum++;

					} else {
						// console.log('Ignored: ' + href);
					}
				}
				return href;
			});

			console.log('Found ' + newLinksNum + ' new links.');
			console.log('Total links = ' + links.length);
			console.log('links seen = ' + Object.size(seen));  // .size() defined later in the script

			if(index !== links.length-1){
				console.log('Crawling next webpage...');
				index++;
				scrapAndCrawl(links);
			} else {
				console.log('scrapAndCrawl COMPLETE!');
				console.log('Updated array of emails', emailAddresses);
				console.log('Found total ' + emailAddresses.length + ' emailAddresses.');

				links.sort(function (a, b){
					return a.localeCompare(b);
				});
				
				console.log('Links crawled: ', links);
				console.log('Total links crawled: ', links.length);
				console.log('Errors: ', errors);

				console.log('ALL SET!');
			}
		});

	} else {

		console.log('Seen already: ' + testLink);

		if(index !== links.length-1){
			console.log('Crawling next webpage...');
			index++;
			scrapAndCrawl(links);
		} else {
			console.log('scrapAndCrawl COMPLETE!');
			console.log('Updated array of emails', emailAddresses);
			console.log('Found total ' + emailAddresses.length + ' emailAddresses.');

			links.sort(function (a, b){
				return a.localeCompare(b);
			});
			
			console.log('Links crawled: ', links);
			console.log('Total links crawled: ', links.length);
			console.log('Errors: ', errors);

			console.log('ALL SET!');
		}

	}
}

scrapAndCrawl(links);
```

Previously, it got stuck at another URL. I tested a couple of other domains and it did not give me any such issues.

I am using Node.js v4.1.1 on OSX Yosemite 10.10.5

How do I fix this?

**Comment by rahul-desai3** [comment]
UPDATE: The same code broke on Ubuntu 14.04 with Node v4.2.1 for this link: http://www.mesotheliomagroup.com/treatment/surgery/epp-vs-pd

**Comment by rahul-desai3** [comment]
UPDATE: After debugging through the error callback I found out the actual error:

```
[Error: Timeout: did not get to load all resources on this page]

/home/rahul/stuff/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^
AssertionError: No open window with an HTML document
    at Browser.queryAll (/home/rahul/stuff/node_modules/zombie/lib/index.js:460:7)
    at /home/rahul/stuff/index.js:76:12
    at done (/home/rahul/stuff/node_modules/zombie/lib/eventloop.js:589:11)
    at timeout (/home/rahul/stuff/node_modules/zombie/lib/eventloop.js:601:33)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by rahul-desai3** [comment]
Setting `waitDuration: 29*1000` fixed it for me.

```
const browser = new Browser({
    waitDuration: 29*1000
});
```

I chose 29 seconds because Heroku has timeout on 30 seconds.
