### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by capaj** [assaf/zombie#965]
Just installed zombie(4.2.1) from npm and tried to run a simple test where I just user browser.visit.
```
ReferenceError: Set is not defined
    at Object.<anonymous> (/home/capaj/c8management/people.io/node_modules/jsdom/lib/jsdom/level2/html.js:238:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/capaj/c8management/people.io/node_modules/jsdom/lib/jsdom/living/index.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/capaj/c8management/people.io/node_modules/zombie/lib/dom/index.js:5:11)
    at Module._compile (module.js:456:26)

```

**Comment by assaf** [comment]
Node 4.0 or later

**Comment by capaj** [comment]
@assaf just realized my mistake. This is what I get for working at Socialbakers, where they are still running everything on node.js 0.10.40. Hence my nvm default is 0.10.40.Thanks anyway
