### ISSUE TITLE
 Parameter 'url' must be a string, not object thrown when using JSPM/SystemJS

### ISSUE THREAD

**Issue by capaj** [assaf/zombie#966]
I get this error when loading my app which is built in JSPM/SystemJS.
Is this a bug in Zombie, or is JSPM loading scripts somehow wrong?
I would suspect the Zombie to be a culprit, because JSPM works just fine in the browser.

```
TypeError: Parameter 'url' must be a string, not object
      at Url.parse (url.js:90:11)
      at Object.urlParse [as parse] (url.js:84:5)
      at Object.Utils.resolveHref (node_modules/zombie/lib/dom/jsdom_patches.js:244:22)
      at new DOMURL (node_modules/zombie/lib/document.js:99:27)
      at l.<anonymous> (http://people.io/jspm_packages/system.js:4:22322)
      at l.<anonymous> (http://people.io/jspm_packages/system.js:4:24654)
      at l.e (http://people.io/jspm_packages/system.js:5:13922)
      at l.normalizeSync (http://people.io/jspm_packages/system.js:5:14081)
      at l.config (http://people.io/jspm_packages/system.js:4:19833)
      at http://people.io/config.js:1:8
      at Object.exports.runInContext (vm.js:44:17)
      at window._evaluate (node_modules/zombie/lib/document.js:253:75)
      at Object.DOM.languageProcessors.javascript (node_modules/zombie/lib/dom/scripts.js:26:12)
      at define.proto._eval (node_modules/jsdom/lib/jsdom/level2/html.js:1477:47)
      at node_modules/jsdom/lib/jsdom/browser/resource-loader.js:32:22
      at Object.item.check (node_modules/jsdom/lib/jsdom/level2/html.js:188:11)
      at node_modules/jsdom/lib/jsdom/level2/html.js:206:12
      at node_modules/zombie/lib/dom/jsdom_patches.js:233:11
      at run (node_modules/core-js/library/modules/es6.promise.js:104:47)
      at node_modules/core-js/library/modules/es6.promise.js:115:28
      at flush (node_modules/core-js/library/modules/$.microtask.js:19:5)
      in http://people.io/app
```

**Comment by assaf** [comment]
Probably a bug

**Comment by chriscantu** [comment]
@capaj I ran into the same problem.  I figured out that SystemJS was passing the jspm loaded dependencies to the DOMURL method in `lib/document.js`.

I did the following locally to work around the problem but this is probably not a ***real*** solution. 

```
// @ line 99
var text = url.toString();
if (base && text.indexOf('@') == 0) url = Utils.resolveHref(base, url);
```

@assaf If you are fine with this approach, I can submit a pull-request.  Otherwise, I would love to hear your suggestions on how best to resolve the problem.  

Thank you!

**Comment by chriscantu** [comment]
Correction:  Looking in master, the change would be on line 60 of document.js

```
   let text = url.toString();
   if (base && text.indexOf('@') === 0)
```

Looking at the contribution guide, it understandably asks for a test.  However, I don't see much in the way of guidance on how the tests should be setup.  I also don't see an existing SystemJS type example.  Guidance?

**Comment by assaf** [comment]
Tests isolate the scenario to the minimum code need to run and yield a positive verification, and then compare the expected behavior to the actual behavior. What you're testing is that the browser behaves according to some existing spec.

**Comment by chriscantu** [comment]
@assaf Thank you for your response.  I understand the scope of testing and its purpose.  I was unclear if there was an existing SystemJS test and how best to write such a test.  I assume the answer is no.  

Since no test exist, I assume I should create a new test specific to SytemJS.  Is that correct?

**Comment by assaf** [comment]
That's the opposite of what I said. SystemJS is not a spec that browsers need to comply with, and bringing in that code base into the test suite is not "minimum code needed to run ...".
