### ISSUE TITLE
How to find a finite resource ?

### ISSUE THREAD

**Issue by sintanial** [assaf/zombie#986]
I have very simple code:
```javascript
const Browser = require('zombie');
const browser = new Browser();

browser.userAgent = "Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30";
browser.visit('http://file-storage.mobi/iYFb7Wsc', function () {
    console.log("LOADEDDDD !!!!", browser.location.href)
});
```

when i run this code with zombie@4.2.1 with DEBUG env, i have this log:

In log i describe my problem.
```
zombie Opened window http://file-storage.mobi/iYFb7Wsc  +0ms
  zombie GET http://file-storage.mobi/iYFb7Wsc => 302 http://aino5.completesecurecarrier.com/?KW={KW}&s1={s1}&s2={s2}&s3={s3}&s4={s4}&s5={s5} +666ms
  zombie GET http://aino5.completesecurecarrier.com/?KW=%7BKW%7D&s1=%7Bs1%7D&s2=%7Bs2%7D&s3=%7Bs3%7D&s4=%7Bs4%7D&s5=%7Bs5%7D => 302 http://BBizz.fucknow.kege.info/?sov=1184950635&hid=brbpjfjffrfrnhhn&&redid=11211&gsid=323&id=XNSX.%7Bs1%7D%3A%3A%7Bs2%7D%3A%3A%7Bs3%7D%3A%3A%7Bs4%7D%3A%3A%7Bs5%7D-r11211-t323 +408ms
  zombie GET http://bbizz.fucknow.kege.info/?sov=1184950635&hid=brbpjfjffrfrnhhn&&redid=11211&gsid=323&id=XNSX.%7Bs1%7D%3A%3A%7Bs2%7D%3A%3A%7Bs3%7D%3A%3A%7Bs4%7D%3A%3A%7Bs5%7D-r11211-t323 => 200 +908ms
  zombie Loaded document http://bbizz.fucknow.kege.info/?sov=1184950635&hid=brbpjfjffrfrnhhn&&redid=11211&gsid=323&id=XNSX.%7Bs1%7D%3A%3A%7Bs2%7D%3A%3A%7Bs3%7D%3A%3A%7Bs4%7D%3A%3A%7Bs5%7D-r11211-t323 +35ms
  zombie Opened window http://bbizz.fucknow.kege.info/MOB505adultrotatorwapALL.html  +22ms
  zombie GET http://bbizz.fucknow.kege.info/MOB505adultrotatorwapALL.html => 200 +2s
  zombie Loaded document http://bbizz.fucknow.kege.info/MOB505adultrotatorwapALL.html +10ms
  zombie Opened window http://www.girlsonfire.mobi/?sl=58919-9eaa6&data1=Track1&data2=Track2&data3=qg108afnDb  +7ms
  zombie GET http://www.girlsonfire.mobi/?sl=58919-9eaa6&data1=Track1&data2=Track2&data3=qg108afnDb => 200 +340ms
  zombie Loaded document http://www.girlsonfire.mobi/?sl=58919-9eaa6&data1=Track1&data2=Track2&data3=qg108afnDb +9ms
  zombie GET http://cdn.mobidea.com/websites-files/resources/js/history_injection.js => 200 +266ms
  zombie Fired setTimeout after 0ms delay +5ms
  zombie Opened window http://2015-2.cftrac.info/aff_c?offer_id=720&aff_id=1052&aff_sub3=%7B%7BAFFILIATE_ID%7D%7D&aff_sub=1005500000002330674-201512-6b6253dc17  +4ms
  zombie GET http://2015-2.cftrac.info/aff_c?offer_id=720&aff_id=1052&aff_sub3=%7B%7BAFFILIATE_ID%7D%7D&aff_sub=1005500000002330674-201512-6b6253dc17 => 302 http://2015-2.cftrac.info/aff_r?offer_id=720&aff_id=1052&url=http%3A%2F%2Fad.blinko.ru%2Fclickforward%3Fcr%3D54875%26transaction_id%3D102df343446f4b87827e6742ae3bba%26aff_id%3D1052&urlauth=397418930219902620270515241089 +251ms

  // [COMMENT FOR GITHUB] THIS REDIRECT 302 FROM 2015-2.cftrac.info TO ad.blinko.ru ------------>>>
  zombie GET http://2015-2.cftrac.info/aff_r?offer_id=720&aff_id=1052&url=http%3A%2F%2Fad.blinko.ru%2Fclickforward%3Fcr%3D54875%26transaction_id%3D102df343446f4b87827e6742ae3bba%26aff_id%3D1052&urlauth=397418930219902620270515241089 => 302 http://ad.blinko.ru/clickforward?cr=54875&transaction_id=102df343446f4b87827e6742ae3bba&aff_id=1052 +348ms

  // [COMMENT FOR GITHUB] THIS browser.visit CALL CALLBACK, BUT WHY ???  ------------>>>
  /------------------------------------/
LOADEDDDD !!!! http://2015-2.cftrac.info/aff_c?offer_id=720&aff_id=1052&aff_sub3=%7B%7BAFFILIATE_ID%7D%7D&aff_sub=1005500000002330674-201512-6b6253dc17
  /------------------------------------/

  zombie GET http://ad.blinko.ru/clickforward?cr=54875&transaction_id=102df343446f4b87827e6742ae3bba&aff_id=1052 => 302 http://ad.blinko.ru/adultshit +351ms
  zombie GET http://ad.blinko.ru/adultshit => 302 http://apps.blinko.ru/page/bonga_cams/2/ +460ms
  
  // [COMMENT FOR GITHUB] THIS IS LAST POINT THAT I NEED, AND THAT I EXPECTED IN browser.visit CALLBACK.  ------------>>>
  zombie GET http://apps.blinko.ru/page/bonga_cams/2/ => 200 +179ms
```

What am I doing wrong ?

**Comment by yaronassa** [comment]
Does .wait help?
For me it solves 99.9% of all the async resource loading issues.
If the regular wait doesn't solve you problem, you can send a wait-function as a parameter, and check for a specific end-flag in the target window. Usually the regular wait will suffice.

```javascript
browser.visit('http://file-storage.mobi/iYFb7Wsc')
.then(function(){
   return browser.wait()
       .then(function(){    
          console.log("LOADEDDDD !!!!", browser.location.href)   
       });
});
```

**Comment by sintanial** [comment]
@yaronassa thx for answer
I ran your code and got this error::

```
Unhandled rejection Error: Timeout: did not get to load all resources on this page
    at timeout (/Users/roman/Projects/*****/*****/********/node_modules/zombie/lib/eventloop.js:601:38)
    at Timer.listOnTimeout (timers.js:93:15)
```

**Comment by yaronassa** [comment]
You could try to find a flag on the page and wait for it.

Most chances that your webpage is trying to do something special that interferes with zombie, and you could manage it with some usage of the .wait function.

There's a very slight chance that you've stumbled on a problem with sub-frames form submission. If the page loads many resources in sub-frames (like ads / remote pixels etc.), this may be the problem (though it's probably something else).

I had to patch document.js to make it work with our testing environment (My original patch is described in https://github.com/assaf/zombie/issues/933, it has changed since then).
I think my changes may harm other parts of zombiejs, so I don't want to offer it as a formal PR.

**Comment by sintanial** [comment]
@yaronassa This pages very simple and don't have sub-frames.
Only in html script like this for redirect user on next page:
```javascript
<html>
....
<body>
....
<script>
window.location.href = "/some_url"
</body>
</html>
```

this happened on 
```
zombie Opened window http://bbizz.fucknow.kege.info/MOB505adultrotatorwapALL.html
....
zombie Opened window http://www.girlsonfire.mobi/?sl=58919-9eaa6&data1=Track1&data2=Track2&data3=qg108afnDb  +7ms
....
zombie Opened window http://2015-2.cftrac.info/aff_c?offer_id=720&aff_id=1052&aff_sub3=%7B%7BAFFILIATE_ID%7D%7D&aff_sub=1005500000002330674-201512-6b6253dc17  +4ms
```

**Comment by yaronassa** [comment]
Ho, sorry, then the solution is much more simple. Change the wait duration:
Add `browser.waitDuration = '20s';` Before performing `.visit`.
Please note that you route through script-heavy locations (like spaces.slimspots.com) that do open some frames as far as I can tell.

**Comment by sintanial** [comment]
@yaronassa yes, waitDuration worked fine, but what it's doing ? why it's not worked without this params ?
And another question, what's really doing method 'wait' ?

**Comment by yaronassa** [comment]
waitDuration relates to the amount of time Zombie will wait for browsing and resource loading responses.
Usually it's not that big of a deal since Zombie is meant to run in testing environments, which are local and fast.
As for the wait function, It's a big subject - I suggest you consult the docs / code.

**Comment by sintanial** [comment]
@yaronassa Unfortunately I could not find documentation on method "wait". Where i can find Full Docs about Zombie ?

**Comment by z-vr** [comment]
on the same note, could somebody explain please why it is not possible to know when all resources have been downloaded and all script been executed, so that we can wait for all these things to happen rather than waiting some constant time?

**Comment by assaf** [comment]
https://github.com/assaf/zombie/blob/master/src/index.js#L242

```
  // Waits for the browser to complete loading resources and processing JavaScript events.
  //
  // Accepts two parameters, both optional:
  // options   - Options that determine how long to wait (see below)
  // callback  - Called with error or null and browser
  //
  // To determine how long to wait:
  // duration  - Do not wait more than this duration (milliseconds or string of
  //             the form "5s"). Defaults to "5s" (see Browser.waitDuration).
  // element   - Stop when this element(s) appear in the DOM.
  // function  - Stop when function returns true; this function is called with
  //             the active window and expected time to the next event (0 to
  //             Infinity).
```

**Comment by sintanial** [comment]
@assaf thx for ref
