### ISSUE TITLE
Correct evaluate js code in href="javascript:"

### ISSUE THREAD

**Issue by sintanial** [assaf/zombie#989]
When i opened site and click to link like this 

```html
<a id="agree" href="javascript:subs()">Save</a>
```

if i evalute this code
```javascript
document.getElementById('agree').click()
```

then in zombie log i see this 

```
  zombie Opened window javascript:subs()  +8ms
  zombie Follow link to javascript:subs() +1ms
  zombie ReferenceError: subs is not defined
    at javascript::1:1
    at Object.exports.runInContext (vm.js:45:17)
    at window._evaluate (/Users/roman/Projects/*****/node_modules/zombie/lib/document.js:253:75)
    at /Users/roman/Projects/*****/node_modules/zombie/lib/document.js:797:16
    at Immediate._onImmediate (/Users/roman/Projects/*****/node_modules/zombie/lib/eventloop.js:676:13)
    at processImmediate [as _immediateCallback] (timers.js:384:17) +14ms
ERROR { '0': { [ReferenceError: subs is not defined] filename: 'javascript:' } } [ { [ReferenceError: subs is not defined] filename: 'javascript:' } ] javascript:subs()

```

**Comment by sintanial** [comment]
every body know how to solve this problem ?
